### ISSUE TITLE
use all relevant images for each source

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#123]
Modify `celeste.jl` to process just light source specified by an objid. Sample usage:

```
./celeste.jl --stage <infer|score> --objid 1237663784214070312
```

For the `infer` stage, `celeste.jl` should use all the relevant images from any run except for the coadd runs (106 and 206).

**Comment by rgiordan** [comment]
Don't you think we should reference objects by the objid rather than their coordinates?

**Comment by jeff-regier** [comment]
That might be better. Does objid uniquely identify the object, or does the same object get assigned different objids if it appears in multiple runs?

**Comment by rgiordan** [comment]
It gets assigned different objids if it appears on multiple runs.  (But it
gets assigned different locations, too.)  For every part of the sky,
there's a "principal" frame (I think that's what it's called), which is
used to choose the "canonical" objids for that section of the sky.  We
should just use the objids from the principal image as unique identifiers.

We should compile a list of redundantly imaged objects with their locations
and canonical objids from the CASJobs database.  All the information is
there, but AFAIK you have to infer multiply-cataloged objects by looking at
their locations.

**Comment by jeff-regier** [comment]
OK, I updated the description

**Comment by jeff-regier** [comment]
@rgiordan -- Did you know of a way to look up the catalog entry given an objid?  (This came up during the conference call.) The catalog files names contain run-camcol-field, right? Is there a table somewhere that maps objid to run-camcol-field?

**Comment by rcthomas** [comment]
Looking at this right now in fact; we can build this catalog easily just iterating over files on disk.  In the dr8 directory I count about 1e6 FITS files.  I can read about 11 files per second with a quick Python script I put together; this would be about 1 day straight to pull out the objid's.  I can easily parallelize this or do it using a faster API or both.  More info later.

**Comment by rcthomas** [comment]
Here is an update.  Each source has a unique thingId, which may correspond to multiple detections, each with its own objID.  I am building an index from thingId to the list of all associated objIds.  I am doing this using the flat files we have on disk, processing them in parallel, as there isn't enough space under myDB on CasJobs to do this.

**Comment by kbarbary** [comment]
I think it would be better to make a patch of sky (e.g., spanning some range in RA and Dec) the unit, rather than a single source.

Advantages:
- This is a better infrastructure for the future when we might want to:
  - incorporate our own source detection, rather than initializing from a pre-existing catalog
  - fit multiple overlapping sources simultaneously
- This will automatically group nearby objects (using the same data) onto the same node, potentially reducing data I/O

I don't think there are any downsides:
- Instead of a look up table of objID-> listof images, we'll have a look up table of sky patch -> list of images. In fact, the table will be smaller.
- The unit of work will be larger (there will be multiple objects per patch of sky), but I think it can still be made small enough for the work to be scheduled efficiently.
- In fact, the scheduler (e.g., Dtree) can potentially have an idea of the runtime of each patch based on the look up table of how many images it includes.

Thoughts?

**Comment by jeff-regier** [comment]
Sounds good to me

**Comment by rcthomas** [comment]
My thoughts are this is depressing because I spent all weekend trying to build this index.

**Comment by jeff-regier** [comment]
I'm not sure this changes whether we need a "thingId -> objid" map, though
we probably no longer need an "objid ->thingId" map.

Kyle, how are you linking objects now in score.jl, between primary and
coadd? Are you doing it by distance? Would joining on "thingId" be
preferable?

**Comment by rgiordan** [comment]
I'm not convinced, but I'm also not quite clear on what exactly you're proposing, Kyle.  Are you just arguing what the input flags for `celeste.jl` should be, or are you proposing some deeper reorganization of the data? 

If I understand right (and please correct me if I don't -- I've been out of the loop) the previous plan was to build a table with rows of:

`thingId (index)`
`list of image files`
`catalog entry`

You would give `celeste.jl` a list of thingIds, and it would get the relevant images and catalog entries, and run the optimization.  Are you now proposing instead that the table should be

`RA, DEC (index)`
`List of tihngIds`
`List of image files`
`List of catalog entries`

If so, I don't think I see what the advantages are (disk IO should be the same in either case), and we have to tie ourselves to a particular.window around an RA / DEC location.  Or have I misunderstood?

I agree that something like this kind of interface will be necessary when we do our own source detection, but that's a ways off.

One way or another, we need to tell Celeste which celestial objects to process within a task, since we are currently tied to a catalog initialization.  These objects need to be identified with some unique identifier, and it sounds like thingId is the way to go.  So Rollin, it seems to me that your work will not be wasted in any case.

**Comment by kbarbary** [comment]
@jeff-regier Currently in scoring, primary is matched to celeste based on objid, and celeste is matched to coadd by distance. If ThingID is universally available as a source identifier, that would be better, but matching by distance is not too bad.

**Comment by kbarbary** [comment]
@rgiordan My understanding of the current plan is that `celeste.jl` gets a _single_ source, not a list. It then has to load (or at least open) the entire image, even though its only going to work on a single source. So if there are 800 sources per image, you're opening that image 800 times.

If instead you give `celeste.jl` a list of sources that are near each other, then that would be mostly equivalent to what I'm suggesting. The differences would be mainly in bookkeeping.

**Comment by rgiordan** [comment]
-- Ryan.  Sent from a phone.  Nevertheless, all typos are deliberate.
On Feb 29, 2016 7:24 PM, "Kyle Barbary" notifications@github.com wrote:

> @rgiordan My understanding of the current plan is that celeste.jl gets a
> single source, not a list. It then has to load (or at least open) the
> entire image, even though its only going to work on a single source. So if
> there are 800 sources per image, you're opening that image 800 times.
> 
> If instead you give celeste.jl a list of sources that are near each
> other, then that would be mostly equivalent to what I'm suggesting. The
> differences would be mainly in bookkeeping.

OK, I see.  It seems to me that the bookkeeping is cleaner if you pass in a
list of sources, which may or may not have been chosen in advance to be
close to one another depending on the needs of the scheduler, than to bake
that logic into celeste.jl.  Flexibility and modularity are good, which I
think points to using thing IDs rather than location as the script input.
Other than the distant eventuality of detecting our own sources, is there
any benefit that you can think of to pass in ra / dec?

**Comment by rcthomas** [comment]
My thinking is that for SC16 we should just move ahead with giving a list of sources and figuring out the scheduling ahead of time.

Just to update everyone I managed to extract the data we need from the files on disk over the weekend, it was about 16 days of CPU time.  The next step is to construct the actual thingId index from that, and I have a schema for HDF5.  I'll just proceed under the assumption we're using that at some point, but if we want anything else let me know.  I can look into ways of making this less painful.

**Comment by kbarbary** [comment]
Yeah lets discuss this later when we get closer to implementing the top level. The main immediate thing is that we need to generalize the code from operating on 5 images (ugriz) to N images. Or is this already possible and I haven't read deep enough into the code?

**Comment by jeff-regier** [comment]
Does anyone know how thingIds get generated? Is it a more sophisticated
process than what Kyle is doing, matching objects by distance?

**Comment by rcthomas** [comment]
Yep, it's this process:

https://www.sdss3.org/dr8/algorithms/resolve.php

**Comment by jeff-regier** [comment]
Nothing in the Celeste statistical model is specific to 1 image in each
band. Some of the code could be, but I think that's easily fixed, if it's
even a problem. Let me know if you have problems and I'll fix it quickly

**Comment by rgiordan** [comment]
Yes, I think that if you give ElboDeriv.elbo a tiled blob with more than
five images and a ModelParams object with patches and tile_sources whose
dimensions match the TiledBlob, it should work.  (Though I haven't tried
it.)  The initialization in initialize_celeste will have to be changed more
substantially, though.
