### ISSUE TITLE
Understand benchmark_elbo.jl run time

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#125]
We expect it to take ~25 seconds, but after the Hessian commit, it takes around ~125 seconds. Because performance with `S=1` matters most now, this issue isn't too pressing. But it would be good to understand what's happening.

**Comment by kbarbary** [comment]
I've been studying the code in ElboDeriv.jl and included files and I have a bit of unsolicited Julia advice. Feel free to ignore if you already know this, or if I'm forgetting something obvious here!

Most of the code seems to be written as functions that update some object, in order to avoid allocating memory. However, in some cases, the code can be rewritten in a more purely functional style without allocating any memory. Here's an example:

``` julia
function eval_bvn_pdf_in_place!{NumType <: Number}(
    elbo_vars::ElboIntermediateVariables{NumType},
    bmc::BvnComponent{NumType}, x::Vector{Float64})

  elbo_vars.bvn_derivs.py1[1] =
    bmc.precision[1,1] * (x[1] - bmc.the_mean[1]) +
    bmc.precision[1,2] * (x[2] - bmc.the_mean[2])
  elbo_vars.bvn_derivs.py2[1] =
    bmc.precision[2,1] * (x[1] - bmc.the_mean[1]) +
    bmc.precision[2,2] * (x[2] - bmc.the_mean[2])
  elbo_vars.bvn_derivs.f_pre[1] =
    bmc.z * exp(-0.5 * ((x[1] - bmc.the_mean[1]) * elbo_vars.bvn_derivs.py1[1] +
                        (x[2] - bmc.the_mean[2]) * elbo_vars.bvn_derivs.py2[1]))

  true # return type
end
```

This function updates 3 numbers in `elbo_vars.bvn_derivs`. It could be rewritten as a non-updating function that simply returns a 3-tuple:

``` julia
function pdf{T <: Number}(bmc::BvnComponent{T}, x::Vector{Float64})
    a = (bmc.precision[1,1] * (x[1] - bmc.the_mean[1]) +
         bmc.precision[1,2] * (x[2] - bmc.the_mean[2]))
    b = (bmc.precision[2,1] * (x[1] - bmc.the_mean[1]) +
         bmc.precision[2,2] * (x[2] - bmc.the_mean[2]))
    c = bmc.z * exp(-0.5 * ((x[1] - bmc.the_mean[1]) * a +
                            (x[2] - bmc.the_mean[2]) * b))
    return a, b, c
end
```

Elsewhere, if you **do** need to store these results in an `ElboIntermediateVariables` instance, you can still do so:

``` julia
a, b, c = pdf(bmc, x)
elbo_vars.bvn_derivs.py1[1] = a
elbo_vars.bvn_derivs.py2[1] = b
elbo_vars.bvn_derivs.f_pre[1] = c
```

When you just want to use these values in some other calculation, you can do so directly. This will save writing to and reading from an array - the values should be passed on the stack. The other advantage of this style is that `pdf()` now doesn't have to know anything about where the result is going to be stored; this is the caller's business.

Of course, there are still places where it makes sense to use updating functions -- mainly when you'd need to allocate a new array to hold the result (when the result consists of many values). When the result is only a few values, you can use tuples instead of an array and avoid the allocation.

**Comment by jeff-regier** [comment]
That seems like a good tip to improve the clarity of the code. But does the
approach you propose, when you do need to store the returned values, copy
the returned value an extra time: first to the stack, and then from the
stack to the heap? Or do both approaches write to the stack first?

**Comment by rgiordan** [comment]
Always good to get advice!  If the answer to Jeff's question is "no", and
the variables don't get copied an extra time (and no memory gets allocated
for them within the function call) then this would indeed be an improvement.

I think most of the functions in ElboDeriv are in fact updating arrays,
though (either of hessians or gradients).

**Comment by kbarbary** [comment]
Pretty sure there's no penalty for this. From http://stackoverflow.com/questions/12766534/cost-of-push-vs-mov-stack-vs-near-memory-and-the-overhead-of-function-calls ...

> If there's a memory cache in the CPU, the stack is likely to be in that cache, unless you allocate and deallocate large arrays or structures on it or have deep function calls or deep recursion, causing cache misses.

`code_native` is fun to look at:

``` julia
# function that returns a 3-tuple (@noinline mimics a more complicated function, making
# sure we still have a function call to look at)
julia> @noinline rand3() = rand(), rand(), rand()
rand3 (generic function with 1 method)

# function that calls the above function and assigns results to an array
# (@inbounds makes the assembly smaller and thus easier to read)
julia> function rand3!(A)
           a, b, c = rand3()
           @inbounds A[1] = a
           @inbounds A[2] = b
           @inbounds A[3] = c
           nothing
       end
rand3! (generic function with 1 method)

# my annotations are on the right
julia> code_native(rand3!, (Vector{Float64},))
    .text
Filename: none
Source line: 2
    pushq   %rbp
    movq    %rsp, %rbp
    pushq   %rbx
    subq    $24, %rsp
    movq    %rdi, %rbx
    leaq    -32(%rbp), %rdi
Source line: 2
    movabsq $139904486102656, %rax  # move the rand3() function pointer to a register
    callq   *%rax   # call the rand3() function
Source line: 3
    movq    (%rbx), %rax
Source line: 2
    movsd   -16(%rbp), %xmm0
    movsd   -32(%rbp), %xmm2
    movsd   -24(%rbp), %xmm1
Source line: 3
    movsd   %xmm2, (%rax)  # assign A[1]
Source line: 4
    movq    (%rbx), %rax
    movsd   %xmm1, 8(%rax)  # assign A[2]
Source line: 5
    movq    (%rbx), %rax
    movsd   %xmm0, 16(%rax)  # assign A[3]
Source line: 6
    addq    $24, %rsp
    popq    %rbx
    popq    %rbp
    ret
```

I don't really read assembly, but as far as I can tell, everything is happening in registers on the CPU between the call to `rand3` and the assignment to the vector. This assembly is minimal.

**Comment by jeff-regier** [comment]
Cool, it looks like this is the way to go.
