### ISSUE TITLE
Unit tests based on synthetic data from GalSim

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#227]
Another benefit of adding these tests: "All the test images in Synthetic.jl use either an identity WCS or a symmetric one. For testing purposes, we should replace them all with an actual asymmetric WCS.", from issue #90 , which this one subsumes.

**Comment by gostevehoward** [comment]
@jeff-regier You still feel good about FactCheck? You mentioned it in #90 and I'll use it for these GalSim-based unit tests unless you've changed your mind.

**Comment by andreasnoack** [comment]
The trend has generally been to use http://docs.julialang.org/en/release-0.5/stdlib/test/#working-with-test-sets instead of FactCheck. They are very similar but the former is part of Base.

**Comment by gostevehoward** [comment]
@andreasnoack OK, thank you! I'll go that route.

**Comment by gostevehoward** [comment]
@jeff-regier Here is a list of all unit tests which use stamps via `SampleData.jl`, organized by which entry point they use:

Unit tests:
* Using `gen_three_body_dataset`
    * `test_derivates.test_box_derivatives`
    * `test_derivates.test_box_simplex_derivatives`
    * `test_derivates.test_fs0m_derivatives`
    * `test_derivates.test_fs1m_derivatives`
    * `test_derivates.test_galaxy_cache_component`
    * `test_derivates.test_galaxy_variable_transform`
    * `test_misc.test_sky_noise_estimates`
    * `test_optimization.test_single_source_optimization`
    * `test_transforms.test_parameter_conversion`
* Using `gen_two_body_dataset`
    * `test_elbo.test_active_sources`
    * `test_elbo.test_num_allowed_sd`
    * `test_elbo.test_populate_fsm!`
* Using `gen_sample_galaxy_dataset`
    * `test_elbo.test_that_galaxy_truth_is_most_likely`
    * `test_log_prob.test_that_gal_truth_is_most_likely_log_prob`
    * `test_optimization.test_full_elbo_optimization`
    * `test_optimization.test_galaxy_optimization`
    * `test_optimization.test_galaxy_optimization_fft`
* Using `gen_sample_star_dataset`
    * `test_derivates.test_brightness_hessian`
    * `test_images.test_stamp_get_object_psf` (**disabled**)
    * `test_infer.test_load_active_pixels`
    * `test_optimization.test_star_optimization`
    * `test_optimization.test_star_optimization_fft`
* Using `load_stamp_catalog` and `load_stamp_blob`
    * `test_elbo.test_coadd_cat_init_is_most_likely`
    * `test_optimization.test_real_stamp_optimization` (**disabled**)
* Using `load_stamp_blob`
    * `test_images.test_set_patch_size` (**disabled**)
    * `test_misc.test_sky_noise_estimates`

Benchmark using `gen_n_body_dataset`:
* `benchmark/speed/benchmark_elbo.jl`

Using `SDSSIO.load_field_images` (not stamps, but relevant):
* `test_images.test_images`
* `test_derivates.test_real_image`

To be clear, are you wanting to replace all these unit tests with versions that use GalSim images? I'm happy to tackle it but want to make sure because it's quite a substantial task. Or are you thinking of just adding some new unit tests that use GalSim images to check basic functionality? That is much easier but doesn't really help us get rid of stamps.

**Comment by rgiordan** [comment]
>
>
>    To be clear, are you wanting to replace all these unit tests with
>    versions that use GalSim images? I'm happy to tackle it but want to make
>    sure because it's quite a substantial task. Or are you thinking of just
>    adding some new unit tests that use GalSim images to check basic
>    functionality? That is much easier but doesn't really help us get rid of
>    stamps.
>
> I don' think replacing all of these with galsim images will be as bad as
you think.  IIRC you only really need to reproduce the functionality of a
few functions in SampleData, i.e.

gen_sample_star_dataset
gen_sample_galaxy_dataset
gen_two_body_dataset
gen_three_body_dataset
gen_n_body_dataset (the randomness is not necessary)
true_star_init

and then maybe also

verify_sample_star and
verify_sample_galaxy

Given what you've already done, I think reproducing that functionality will
be pretty straightforward.  (You may want to choose a small PSF, like a 1.5
pixel sd.)  Then the rest of the tests can be left unchanged, and the rest
of SampleData.jl and Synthetic.jl can just be deleted.

Ryan

**Comment by jeff-regier** [comment]
Let's make this issue about adding new tests based on galsim rather than about deleting old tests that rely on stamps. I agree with Ryan that deleting stamps is not as bad as it sounds, but other issues may give us more benefit. Let's reassess once the galsim unit tests are in place.

**Comment by gostevehoward** [comment]
PR #452 I just sent moves `GalsimBenchmark.jl` into `src/` and adds a simple "unit test" that exercises the GalsimBenchmark code for two GalSim test cases and checks the results aren't way off.

On the one hand I could write more detailed tests of Celeste's internals using GalSim images, or port the existing ones, but it sounds like the call is that's not worth the time right now.

On the other hand I could write proper unit tests that exercise the internals of `GalsimBenchmark.jl` in a more piecemeal manner. For a fairly straightforward benchmark script (rather than a piece of core Celeste) that seems not worthwhile to me, but I'm happy to add some.

So I'm not sure if this is exactly what you wanted, let me know.

This isn't terribly important but I can't not mention it: I wouldn't technically this sort of thing a *unit test*, I think the term unit test should really refer to code that exercises a relatively small piece of code *in isolation*. Unit tests should all be very, very fast, should never do I/O, and should be as focused as possible---without being so tightly coupled to implementation details as to become highly brittle, or being so finely focused that they test obvious things (there's always a tradeoff). Larger tests, slower tests, and/or tests that do I/O all have their place, but I would call them integration tests or functional tests and treat them separately. Probably sounds like I'm just picking on terminology, but differentiating between these is important for the long-term utility of a test suite, in my experience. Also, writing proper unit tests requires changes to the way we design the code under test, almost always for the better (it forces you to improve modularity). I don't propose any sweeping changes since there are a lot of urgent tasks on our plate, but figured I'd throw the idea out there if anyone's interested. I also acknowledge this is largely a subjective matter and prevailing opinions vary among different language and application communities :)

**Comment by jeff-regier** [comment]
Hi Steve, It's probably best if you decide whether to add more tests or to move on to #157. If it's easy to make the tests way better then that could be worth doing while it's on your mind. Or you could open new issues so we get back to it in the future. Or we could close this issue if the low hanging fruit is gone and move on.

I'm glad to hear about the distinction between unit tests and integration/functional tests. We should probably have a more coherent testing strategy eventually. If you have ideas already, you could open issues for them. When the code is more mature and we have astronomers contributing code, then there will be an additional reason to have more thorough testing.
