### ISSUE TITLE
BoundsError in Optim/src/newton_trust_region.jl:102

### ISSUE THREAD

**Issue by gostevehoward** [jeff-regier/Celeste.jl#292]
I'm trying to run Celeste on a very simple synthetic galaxy image with simple settings. Depending on the position parameters in the catalog entry, sometimes it runs, and sometimes it does this:

```
17:01 steve@fisher:~/work/Celeste.jl/benchmark/galsim$ julia bug_repro.jl
INFO: f_evals: 10 value: -664288.3457243084
ERROR: LoadError: BoundsError: attempt to access 0-element Array{Float64,1} at index [1]
 in getindex(::Array{Float64,1}, ::Int64) at ./array.jl:383
 in #solve_tr_subproblem!#37(::Float64, ::Int64, ::Function, ::Array{Float64,1}, ::Array{Float64,2}, ::Float64, ::Array{Float64,1}) at /home/steve/.julia/v0.5/Optim/src/newton_trust_region.jl:102
 in optimize(::Optim.TwiceDifferentiableFunction, ::Array{Float64,1}, ::Optim.NewtonTrustRegion{Float64}, ::Optim.OptimizationOptions{Void}) at /home/steve/.julia/v0.5/Optim/src/newton_trust_region.jl:302
 in optimize(::Function, ::Function, ::Function, ::Array{Float64,1}, ::Optim.NewtonTrustRegion{Float64}, ::Optim.OptimizationOptions{Void}) at /home/steve/.julia/v0.5/Optim/src/optimize.jl:129
 in #maximize_f#16(::Array{Int64,1}, ::Float64, ::Float64, ::Bool, ::Int64, ::Float64, ::Bool, ::Function, ::Celeste.ElboDeriv.#elbo_likelihood, ::Celeste.ElboDeriv.ElboArgs{Float64}, ::Celeste.Transform.DataTransform) at /home/steve/.julia/v0.5/Celeste/src/OptimizeElbo.jl:226
 in (::Celeste.OptimizeElbo.#kw##maximize_f)(::Array{Any,1}, ::Celeste.OptimizeElbo.#maximize_f, ::Function, ::Celeste.ElboDeriv.ElboArgs{Float64}, ::Celeste.Transform.DataTransform) at ./<missing>:0 (repeats 2 times)
 in main() at /home/steve/work/Celeste.jl/benchmark/galsim/bug_repro.jl:83
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/steve/work/Celeste.jl/benchmark/galsim/bug_repro.jl, in expression starting on line 86
```

I've attached a "minimal" repro case (it's not small but I don't know how to run Celeste with less code :). The ZIP contains one script for running Celeste and one FITS image:

[optim_bounds_error_repro.zip](https://github.com/jeff-regier/Celeste.jl/files/473681/optim_bounds_error_repro.zip)

FYI, I'm on [this commit](https://github.com/gostevehoward/Celeste.jl/commit/9f29dce12884119989cd437e99eb3c9ec8bc26b6) in my fork, and

```
$ julia --version
julia version 0.5.0-rc3
```

**Comment by rgiordan** [comment]
I'm taking a look now.

**Comment by rgiordan** [comment]
The Hessian is full of NaN at the initial point, as revealed by running
verbose:

OptimizeElbo.maximize_f(ElboDeriv.elbo_likelihood, ea, loc_width=1.0,
verbose=true)

That will certainly screw things up.  Now looking into why that is
happening.

**Comment by rgiordan** [comment]
Ok, evidently the Hessian calculation doesn't support zeros in alphaBar.  I
have to run so I can't say at the moment why that is, but at least it
allows the optimization to run.  (It also diverges, but Steve, you can
presumably work from there.)

Make alphaBar [0.33, 0.33, 0.33] and it at least runs.

**Comment by rgiordan** [comment]
After looking into it a bit this morning, the alphaBar thing seems to be a
red herring.  Zero alphaBar is actually fine in the Hessian, and it just
looks like the optimization is going off the rails.

I'm still looking at it, but I wanted to keep you up to date, Steve.

**Comment by rgiordan** [comment]
Ah, my confusion yesterday was caused by the fact that when vp is in the
global scope (as it is when I'm debugging), it gets updated in place when
you run the optimization, so I was in fact evaluating the log likelihood at
the point reached by the optimization and not the initial point.  Gross.

**Comment by rgiordan** [comment]
I've tracked it down to a couple different things.  Primarily the problem
is caused by an unrealistic initialization point.  Steve, you should know
that Celeste is currently extremely non-robust to poor initializations, and
what is happening here is pretty representative -- if it can't fit the
image, it drives parameters to crazy values, eventually hits numeric
problems, and returns NaN.  This isn't very friendly behavior, but since
we're using catalog inits improving it hasn't been a priority yet.

The main culprit is the choice of fluxes.  Since you're repeating the same
pixels for every band, the fluxes in the test file are completely
non-representative.  By replacing them with the heuristically chosen

sample_star_fluxes = Float64[ 7 \* maximum(pixels) for b=1:5 ] / 1000
sample_galaxy_fluxes = sample_star_fluxes

gives a working optimization.  Also, note that a good estimate of the "true
location" is more than one pixel away from your initial starting point:

true_pix_loc = ind2sub(size(pixels), findmax(pixels)[2])
true_world_loc = WCS.pix_to_world(wcs, Float64[true_pix_loc[1],
true_pix_loc[2]])
pix_loc = WCS.world_to_pix(wcs, vp[1][Celeste.ids.u])
julia> pix_loc - true_pix_loc
2-element Array{Float64,1}:
 -1.0
  1.33333

...so in the optimization you should set loc_width to be something bigger
than one (say, three).  This wasn't causing NaNs, but it's worth pointing
out.

Ultimately, the NaN in the objective was caused by e_scale being driven too
low.  I'm not sure why that is, but in the future we may want to change the
initialization from 0.2 or have a higher lower bound in the transform.

I don't mind helping, but here are some helpful tools for debugging these
kinds of problems yourself in the future:

# The verbose option of maximize

OptimizeElbo.maximize_f(ElboDeriv.elbo_likelihood, ea, loc_width=3.0,
verbose=true)

# View variational parameters with names

DataFrame(id_name=Celeste.Model.get_id_names(Celeste.Model.CanonicalParams()),
vp=vp[1])

# View a predicted and actual image using PyPlot

pred_pix = Celeste.ElboDeriv.tile_predicted_image(ea.images[5].tiles[1, 1],
ea, [1], include_epsilon=true);
pix_loc = WCS.world_to_pix(wcs, vp[1][Celeste.ids.u])
matshow(pred_pix); colorbar(); plot(pix_loc[2] - 1, pix_loc[1] - 1, "ro");
title("Predicted")
matshow(pixels); colorbar(); plot(pix_loc[2] - 1, pix_loc[1] - 1, "ro");
title("Actual")

Ryan
