### ISSUE TITLE
learn the point spread function

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#3]
The SDSS pipeline doesn't approximate the PSF exclusively with Gaussians, so we need to fit a Gaussian mixture model ourselves. [GaussianMixtures.jl](https://github.com/davidavdav/GaussianMixtures.jl) looks useful.

**Comment by rgiordan** [comment]
I think this will require both loading a field and a catalog.  The load_catalog function seems to be out of date, or at least doesn't match the file calibPhotomGlobal-003900-6.fits in the sample_field directory -- can you point me to some reading about how to fix it up?

**Comment by jeff-regier** [comment]
Yeah, "calibObj-..." is different than "calibPhotomGlobal-...". I wrote `load_catalog` with the former in mind. I might have excluded "calibObj-..." from github because it's large.

http://data.sdss3.org/datamodel/files/PHOTO_SWEEP/RERUN/calibObj.html

I found some calibObj files here:

http://data.sdss3.org/sas/dr12/boss/sweeps/dr9/301/

These are the ones you want for `sample_field`:

http://data.sdss3.org/sas/dr12/boss/sweeps/dr9/301/calibObj-003900-6-star.fits.gz
http://data.sdss3.org/sas/dr12/boss/sweeps/dr9/301/calibObj-003900-6-gal.fits.gz

Just came across this page...might be useful.
http://www.sdss.org/dr12/imaging/imaging_access/

**Comment by rgiordan** [comment]
For reference, there is an issue reading in the psField files:
https://github.com/JuliaAstro/FITSIO.jl/issues/33

**Comment by jeff-regier** [comment]
I think I was able to read in variable length fields using the low level table interface. There may be an example of how to do it the `load_field` function.

**Comment by rgiordan** [comment]
That may be true, though all the "field*.fits" fields currently load fine with the high-level FITS library, so I suspect a problem may remain.  I asked that in the other thread.  Let's see what the FITS guys say.

**Comment by rgiordan** [comment]
It turns out that, like iota and epsilon, the PSF varies over the image, which opens the question of how to store and read it.

I think the right way is to store the Gaussian parameters in a coarse grid and use linear interpolation.  At the start of an ELBO evaluation, I'll evaluate the PSF at our current beliefs of the source locations, so that for the purpose of the ELBO, the each source will have its own PSF.

**Comment by jeff-regier** [comment]
How about estimating the PSF at each known star in the catalog (or some
subset of them...say, the brightest, most isolated stars) and then using a
Gaussian Process to interpolate the PSF at points in between them?

**Comment by rgiordan** [comment]
That seems a bit heavy-handed.  I think you need a Gaussian Process if you are uncertain about points in between your observation -- we have a data structure parameterizing SDSS's belief about the true PSF for every point in the image*.  The only question is how to to store it.
- The way they actually store the PSF is a bit different from how you described it to me, so maybe that's the source of the confusion.  I tried to document it in the SDSS library of the wcs branch if you want to check it out.

**Comment by jeff-regier** [comment]
Isn't SDSS's representation of the PSF a mixture of 2 Gaussians and a power
distribution? I thought we needed to learn the PSF ourselves (from the
known stars), because we model the PSF as a mixture of 3 Gaussian. (?)

**Comment by rgiordan** [comment]
There may be multiple versions of the PSF floating around in SDSS files, and some of them might be mixtures of two Gaussians and a power law.  However, the psField files contain information necessary to reconstruct "images" of the PSF, in the sense that they tell you what a picture of a point source, taken through the optics, would look like at any point in the image.

These images are 51 x 51, and are represented as a weighted function of four basis images (they call them "eigenimages"), where the weights vary smoothly over the image as a fourth-order polynomial in x and y, the location of the point source.  At some point this is presumably calculated by looking at the images of isolated, bright stars, but SDSS has already done that work for us.

Taking this as a ground truth, we can represent it however we want.  Specifically, we can fit a mixture of Gaussians to the provided 51 x 51 image.  But since this changes over the image, we will have a different mixture of Gaussians at different points.

**Comment by jeff-regier** [comment]
I see...sounds like we should fit a mixture of 3 Gaussians for each source
then, as you suggest. It might be worth checking with Dustin first though.
For the stamps, I thought he fit the PSF using known stars rather than
using SDSS "eigenimages". There might be a reason he did that. (Or I could
be mistaken about what he did.)

**Comment by rgiordan** [comment]
This is resolved in 1ae4487d7e45403d7a08bf5ee4e494c50e865281 (modulo issue

**Comment by rgiordan** [comment]
Sorry, I accidentally closed this -- I see that putting the multiple values in the Image type is also part of this issue.

**Comment by rgiordan** [comment]
Actually, I'm going to close this and make the non-constant PSF a separate, lower-priority issue since it'll be a bookkeeping headache.  I suspect that for now just using a constant PSF chosen from the middle of the image will do.
