### ISSUE TITLE
Matrix-valued iota and epsilon

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#32]
Since in real images the sky background and calibration vector vary across the image, perhaps these quantities should be matrix-valued, not scalar-valued, in ElboDeriv.

I think iota should definitely be matrix-valued, since it varies quite a lot across the sky.  We can pass around a CoordInterpGrid object instead of the full matrix, since that's all that's saved in the FITS file anyway.

The calibration vector -- which is the only variable part of epsilon -- only varies across a row, and it doesn't vary much (see attached).  Perhaps we could get away with using its average if you wanted to.

Jeff, any thoughts before I jump in?

![calib_vector](https://cloud.githubusercontent.com/assets/4494910/7641783/d8fe9d28-fa40-11e4-9b4d-6081ccc0c128.png)

**Comment by jeff-regier** [comment]
I'm not sure whether the intra-image variation in calibration vector ever matters....Let's ask Dustin about this tomorrow.

**Comment by rgiordan** [comment]
How about the sky background?  If we store the whole background as a full-sized matrix, we double the amount of data in memory, but if we only store the bilinear object, we need to compute a bilinear interpolation for every point for every ELBO calculation.  I'm inclined to store the whole matrix and save on CPU, but I'd be interested to hear what you think is best.

**Comment by jeff-regier** [comment]
Another option is computing the sky background once per tile, rather than once per pixel.

Either way---as you note---we have to decide whether to pre-compute it for each tile/pixel, or to recompute it for one pixel each time we evaluate the ELBO at a pixel. It probably won't be a memory or a CPU bottleneck either way, at least unless it's much faster to compute the interpolation for every point all at once (as a batch), than to compute it for each point at different times. In the former case, we should definitely pre-compute it. In the latter case, I'd lean towards re-computing it every time...memory access is likely slower than an easy calculation.

**Comment by rgiordan** [comment]
This is done in https://github.com/jeff-regier/Celeste.jl/pull/39, though for now I am just pre-computing the whole thing.  We are currently definitely CPU bound, not memory bound.  It will not be hard to do something different later if we find that we need to.
