### ISSUE TITLE
e_scale is misestimated

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#348]
We overestimate galaxies' scales, both according to stripe 82 and now on galsim data. I'm not sure what it will take to fix the `e_scale` issue....maybe the new PSF will help, maybe priors on all the galaxy parameters would make a difference, or maybe we need to increase the variance of pixels around galaxies to account for an overly simplistic galaxy model (in addition to the Poisson noise that we already account for).

**Comment by rgiordan** [comment]
Just to document here what we talked about on the call this week: this is a good point, but it may be a little premature.

First of all, we can add a prior without making `e_scale` random.  The ELBO contains an expected log prior and an entropy term, which we are currently wrapping into a single KL divergence between the prior and variational distribution.  However, there is no reason we can't just add an expected log prior on a parameter fit with a MAP estimate.

Given this, the only reason we'd make `e_scale` random is if (1) the means are incorrect relative to MCMC, and we think they can be fixed if e_scale has nonzero variance or (2) the posterior covariance is wrong relative to MCMC and it can't be fixed with LRVB.  Either of these could well be the case, but I think that before we jump through the hoops to make `e_scale` stochastic there's evidence that there's a real need.

So I propose trying adding a prior for the time being and revisiting this question when @andymiller has MCMC working.

**Comment by jeff-regier** [comment]
Solved by @gostevehoward along with #437 .  Fixed in PR #441.
