### ISSUE TITLE
load_active_pixels! only works with a single active source, unit tests for Infer.jl

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#355]
`load_active_pixels!` only gets the active pixels for the first active source.  This probably slipped past because it and the other functions in `Infer.jl`, are also missing tests.

**Comment by jeff-regier** [comment]
There's an assert statement in `load_active_pxiels!` that ensures only 1 source is active. PR #363 adds a basic unit test for `load_active_pixels!`. 

As for the other functions in `Infer.jl`,  there's `infer_source()`, which gets run in `test_infer.jl`. That in turn calls all the other functions in `Infer.jl`, so at least their syntax gets checked. Not saying that's good enough, but it's a lot better than not having the syntax checked by the tests. `fit_object_psfs!()` is really simple / algorithmic---I don't know that it warrants a test beyond the test that runs `infer_source()`. `get_tile_source_map()` is going to change entirely with #316. `find_neighbors()` should be tested, the perhaps after #142? OK if we close this issue and open one specific to testing `find_neighbors()`?

**Comment by rgiordan** [comment]
This function should set active pixels for multiple sources if requested.  It is not hard to do.  The code that you refactored did it, so I'm really requesting that you restore deleted functionality rather than implement new functionality.  When we look into doing per-source coordinate ascent vs joint optimization on multiple sources we will want to have this.  Please fix this.

Regarding testing, per our discussion at lunch today, we have different ideas about the value of unit tests.  If I were you, I would restore the full functionality of the old tests (that the active pixels actually catch most of the light, that the ELBO is about the same, and that the min_radius works as advertised).  But this is your code, so if you don't think those tests are important, it's your call.

**Comment by jeff-regier** [comment]
PR #363 adds the additional test you mention and restores support for multiple active sources. As originally implemented, the `intersect` command was allocating a huge amount of memory. That's partly why I removed support for multiple sources during the IPDPS push to lower memory allocation. The current code avoids using `intersect` with by using an `in` statement for each active source. Because we'll never have many active_sources (or else we're in trouble because the hessian will be huge), this should be pretty fast. But let me run `benchmark_infer.jl` before merging PR #363.
