### ISSUE TITLE
Break up ```ElboIntermediateVariables``` so the ```elbo_objective.jl``` code can be more modular

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#359]
@jeff-regier , what do you think?  As a use case, note that using a convolved PSF has a different way of storing the `fsm` data than a vector over sources.  I think we should have a separate intermediate variables type for the elbo, the E_G, the fsm, and the bvn calculations.

**Comment by jeff-regier** [comment]
@rgiordan -- I'm not sure I understand this issue. Is this something you'd like me to work on? Now that, to avoid memory allocations, we're storing `ElboIntermediateVariables` instances in the `ElboArgs` instance, should we get rid of  `ElboIntermediateVariables` and put those pointer in `ElboArgs`? (Is that what you had in mind?)

**Comment by rgiordan** [comment]
Sorry I didn't reply to this.  For an example of what I'm talking about, take a look at ```add_elbo_log_term!```.  We pass in an entire ```ElboIntermediateVariables``` object, which contains quite a lot of stuff, in order to access a small number of pre-allocated memory for temporary storage, e.g. ```combine_grad``` and ```combine_hess```.  Where I needed to (like ```calculate_var_G_s!```) I just pulled those variables out.  We can keep doing that piecemeal if you're happy with the design as-is.  Up to you.

**Comment by jeff-regier** [comment]
I worked on making `ElboArgs` a type parameterized by the type of the PSF, so that code general to both PSF methods runs on either type of `ElboArgs`, and code specific to each PSF method ("MOG" or "FFT") has all the values it needs (and allocates no extra memory for the other type of PSF). It isn't easy doing this retroactively, unfortunately. I think the piecemeal approach with a bunch of extra variable, inelegant though it is, is probably the most efficient way to go. I'm still hopeful that we can get the FFT approach to a point where it's so much better than the MOG that we can delete the MOG code, so I don't want to put too much effort into developing a clean way to have the code base support both PSF models.
