### ISSUE TITLE
compute runtime of a Hessian-vector multiply for the ELBO with ForwardDiff

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#380]
If we multiply the gradient by the Hessian in about 2x the time it takes to compute the gradient, and CG needs about 10 iterations, that we could compute newton steps in about 20x the time of computing the gradient...for an arbitrary number of active sources. Trust region Newton's method would require more multiplying I think, so this may not be a viable path forward, but it seems worth considering. Not having to manually code changes to the Hessian would make it much easier to experiment with different models too.

**Comment by jrevels** [comment]
Also keep in mind that https://github.com/JuliaDiff/ReverseDiff.jl is basically ready and tested, and supports full tape/graph reuse as well as linear algebra optimizations. It's generally as faster or faster than JuMP's AD for the gradients I've benchmarked, though it only has extremely naive sparsity exploitation compared to ReverseDiffSparse, so Hessians might be weaker for now.

Right now I'm writing docs for it and its dependencies, which is why it's not yet registered. If you want to play around with it, you can checkout the `jr/diffbase` branch on ForwardDiff and clone https://github.com/JuliaDiff/DiffBase.jl. I'm hoping to have everything registered by the end of the week.

**Comment by jeff-regier** [comment]
This is done on the `jcr/cg` branch. It works well.
