### ISSUE TITLE
use multiple threads for a single component

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#393]
Some components will be too large to process with a single thread (or with a single node). Here's an example of a globular cluster:

![globular cluster](http://www.capitalberg.com/wp-content/uploads/2016/01/Generations-of-Stars-Are-Born-in-a-Single-Globular-Cluster-1024x576.jpg)

Though every star is connected to its neighbors, every star isn't connected to every star, i.e. the component is not a clique. Therefore, we should be able to use a lot of threads to optimize stars concurrently.

**Comment by agnusmaximus** [comment]
I think I mis-stated the algorithm during the conference call yesterday, sorry about this! Cyclades samples batches of light sources from the overall total light sources. Then it creates a conflict graph from the light sources only in those batches. 

This means in the case above, while the overall graph is a single connected component, sampling randomly from say a batch size of 500 will most likely result in a sampled graph with many individual connected components (each of which can be processed in parallel). So the issue of having a denser conflict pattern (and possibly a fully connected graph) can be solved by tuning the batch size so that the resulting sampled graph has many connected components.

Smaller batch size often means more connected components in the batch, while large batch sizes often means less connected components (with more imbalance in the size of the connected components of the batch). For example, at the extreme end, setting batch size to be the total number of light sources to be processed would yield 1 single connected component as pointed out. This also implies that using a smaller batch size is more amenable to load balancing, since the resulting connected components within that batch are smaller and more equal in size.

So in the case above, all we need to do is tune the batch size for the existing code to be as large as possible (we want to minimize the total number of batches, since there are implicit computation barriers between processing batches, adding computational overhead), but that will still yield a good load balance between threads. Setting batch size to be the total # of light sources is definitely not a good choice, as pointed out in this example everything is 1 connected component, meaning one thread would process all the light sources while the others would be idle.

So a run through of the cyclades algorithm:
Say there are 1000 total light sources we are trying to optimize, and the batch size is 100. 
We divide the 1000 total light sources into batches of 100 elements randomly, so there are 10 batches each with 100 light sources.
For each batch we compute the conflict graph of light sources only within the batch we are looking at. Then we load balance connected components across threads. 
Then during optimization, all the threads would process the light sources assigned to them in batch 1 (in parallel), wait until everyone was finished, then start batch 2 and so on. 
Note that there may be conflicts between light sources of different batches, which is why we add an implicit thread barrier between batches.

**Comment by jeff-regier** [comment]
Ah, I get it now. Thanks for the explanation.

We may want to select our "batches" to include mostly sources that are near each other, so we don't have to load a lot of new data for each sample from the batch. 

We may not want to form our sampled graph by sampling uniformly from the batch either: it's more important to optimize a big galaxy that has a bunch of stars in front of it right away, than to optimize the stars, because the stars won't have the right brightness until the galaxy does. I wonder if there's a principled way to encode that intuition. Lots to discuss tomorrow!
