### ISSUE TITLE
Flexibly specify the ELBO function and initialization

### ISSUE THREAD

**Issue by rgiordan** [jeff-regier/Celeste.jl#456]
I'd like to be able to flexibly specify alternative version of the ELBO function for stripe 82, the galsim benchmarks, and ordinary SDSS data.  Right now, the DeterministicVI ELBO is hard coded in a variety of places.

@jeff-regier , you have strong opinions about how to organize things, so I think it's best to let you handle this.  The ideal solution in my opinion would be a user-specifiable callback taking an ElboArgs and returning an optimized ELBO.

**Comment by jeff-regier** [comment]
I'd prefer to remove the hard coded settings, and make them variables in `ElboArgs`, rather than making multiple versions of the source code. Then you'd initialize `ElboArgs` differently depending on whether you're running on stripe 82, galsim, or SDSS. (Since the point of the galsim/stripe82 benchmarks is to validate the code that we're using in production, we want to minimize differences between the environments.) What hard coded settings need to vary depending on the dataset?

It would be even better if we could make the galsim data look so much like the actual SDSS data that we didn't even need different settings. It may be slightly more work but then the validation and the production routines can't get out of sync.

**Comment by rgiordan** [comment]
Sorry, I think I wasn't clear.  I would like to run stripe 82 and the galsim data with my new PSF ELBO, which is both different from ```DeterministicVI.elbo``` and requires data not currently in ```ElboArgs```.

Here's how it seems to work now.  The stripe 82 validation function calls ```ParallelRun.infer_field```, which calls ```ParallelRun.one_node_infer```, which calls ```ParallelRun.parallel_infer```, which then calls ```ParallellRun.one_node_single_infer```, which calls ```DeterministicVi.infer_source```, in which the call to ```DeterministicVi.elbo``` is hard coded.

The Galsim benchmark calls its own ```parallel_inference``` function, which calls ```ParallelRun.parallel_infer```, and from there follows the path above unless it's running joint inference.  If it is, it calls ```one_node_joint_infer``` from the Cyclades script, which itself hard codes the call to ```DeterministicVI.elbo```.

On actual data, you call ```infer_box``` or ```infer_rcf```, both of which call ```ParallelRun.one_node_infer``` and so enter the first chain of functions.

It would be pretty nice if one could somehow specify more flexible initialization and elbo functions without touching all of the functions in this chain.  (You can see the unit tests to see what is necessary.)  It will be especially useful going forwards if I (or other people) are using Celeste as a platform for experimenting with new algorithms and not just a catalog generator.

It also seems to me that perhaps this whole setup could be simplified and clarified some, but that's more up to you.

**Comment by rgiordan** [comment]
I didn't realize this before, but you didn't implement this for ```one_node_joint_infer```.  I'll re-open the issue as a placeholder until you get a chance to do that.

**Comment by jeff-regier** [comment]
I'm working on it but let's make it a new issue. I already spent too long on this one :-(
