### ISSUE TITLE
store galaxy effective radius in arc seconds, not pixels

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#571]
Apparently pixels are not all 0.396 arc seconds in height and width. It depends on `cosd(declination)`, and the orientation of the image. Therefore there's no single galaxy radius in pixel units. To fix this problem, let's store the galaxy radius in `vp` in arc seconds.

**Comment by rcthomas** [comment]
Pixel scale is fixed by the detector manufacturing and the telescope optics, it doesn't know where the telescope is pointing.  So that's not the explanation, I think you just don't mean "pixel scale."  A clue is that there is "no single galaxy radius" in any units, not sure what you mean here.  But ultimately, just store it in arc-seconds, it probably fixes whatever's wrong.

**Comment by jeff-regier** [comment]
OK, I think I got it now: pixels *are* all 0.396 arc seconds in height and width. But that doesn't mean that if you compare the ra/dec coordinates of the adjacent corners of a pixel, either ra or dec will differ by 0.396 arc seconds. The latter statement will hold near the equator, for axis aligned images, but it doesn't hold in general.

@rcthomas -- Is this right? These units issues are pretty tricky for non-astronomers.

**Comment by rcthomas** [comment]
Yes that is right.  And the units are tricky for astronomers too.

**Comment by jeff-regier** [comment]
OK now that I understand the issue, it isn't really so bad to store the radius in pixel units.
