### ISSUE TITLE
Examine background variability in synthetic imagery

### ISSUE THREAD

**Issue by gostevehoward** [jeff-regier/Celeste.jl#655]
Jeff noted in #625 that the variability for background pixels looks maybe off in synthetic imagery.

**Comment by gostevehoward** [comment]
I had to spent some time untangling the puzzle of gain, calibration, photo-electrons, counts, data numbers, nanomaggies, iota, epsilon, etc., in order to actually attack this problem. I documented it all [here](https://github.com/jeff-regier/Celeste.jl/wiki/About-SDSS-and-Stripe-82) and added pointers to the [glossary](https://github.com/jeff-regier/Celeste.jl/wiki/Glossary-and-guide-to-Celeste-parameters). (I will correct some misnamed vars in the code too, and add comments with units of the various fields.)

**Comment by jeff-regier** [comment]
Glad you were able to figure it out. I regret introducing Celeste-specific variables epsilon and iota into the Celeste code, with their own definitions, rather than just sticking with the SDSS conventions throughout. It seemed like a good idea at the time.

I'm still a little fuzzy about the distinction between count and `nelecs`. They differ by a factor of around 4 usually (the gain). They can't both be Poisson. I think empirically `nelecs` was nearly Poisson (i.e. mean = var) and count wasn't. But if "count" means the number of electrons detected, rather than extrapolated, then that's the quantity that should be Poisson.

**Comment by gostevehoward** [comment]
To be honest I'm not sure about the scientific meaning of "counts" (DNs) vs. nelecs (number of photo-electrons). The SDSS docs are unambiguous, however, about the fact that "the number of photo-electrons is the quantity that is statistically Poisson distributed": https://data.sdss.org/datamodel/files/BOSS_PHOTOOBJ/frames/RERUN/RUN/CAMCOL/frame.html (that's the page I linked to in the new wiki entry). Does that clear things up? Or maybe I'm not understanding the question?

For what it's worth, that page also mentions additional "dark variance" added to the Poisson noise; I don't know if we try to handle that or if it's important.

**Comment by jeff-regier** [comment]
Oh that's right, nelecs it is. No idea what counts are then, but maybe it
doesn't matter. Dark variance is supposed to be small, and getting smaller in
future surveys, so we ignore it. But it could explain why we underestimate
variance by 10% or so.

**Comment by gostevehoward** [comment]
Resolved by #667, I think
