### ISSUE TITLE
restore performance of benchmark.jl

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#67]
Looks like `bin/benchmark.jl` is taking 6x as long now to compute the elbo as it did at the end of May. Deepcopy operations may be to blame:

```
  9909 deepcopy.jl                _deepcopy_t                                36
  9999 ...ste/src/CelesteTypes.jl +                                         619
 10171 ...eleste/src/ElboDeriv.jl accum_pixel_source_stats!                 558
 10248 ...eleste/src/ElboDeriv.jl accum_pixel_source_stats!                 567
 10668 deepcopy.jl                deepcopy_internal                          24
 11029 ...eleste/src/ModelInit.jl initialize_model_params                   394
 11043 ...eleste/src/ModelInit.jl initialize_celeste                        347
 11099 ...leste/src/SampleData.jl gen_n_body_dataset                        159
 13327 ...eleste/src/ElboDeriv.jl get_tile_sf                               813
 14513 ...eleste/src/ElboDeriv.jl accum_pixel_source_stats!                 569
 14685 ...ste.jl/bin/benchmark.jl small_image_profile                        15
 15183 ./boot.jl                  include                                   245
 15183 ./client.jl                process_options                           285
 15183 ./client.jl                _start                                    354
 15183 loading.jl                 include_from_node1                        128
 15183 profile.jl                 anonymous                                  14
 15934 ...eleste/src/ElboDeriv.jl accum_pixel_source_stats!                 570
 23063 ...eleste/src/ElboDeriv.jl accum_galaxy_pos!                         453
 26882 ...eleste/src/ElboDeriv.jl accum_galaxy_pos!                         454
 69416 ...eleste/src/ElboDeriv.jl accum_pixel_source_stats!                 518
155984 ...eleste/src/ElboDeriv.jl expected_pixel_brightness!                650
156413 ...eleste/src/ElboDeriv.jl tile_likelihood!                          715
165874 ...eleste/src/ElboDeriv.jl get_tile_sf                               815
195042 no file                    anonymous                                 820
195045 multi.jl                   anonymous                                1279
195045 multi.jl                   run_work_thunk                            621
195046 multi.jl                   run_work_thunk                            630
195046 task.jl                    anonymous                                   6
```

**Comment by rgiordan** [comment]
Testing the whole setup process is an unfair comparison -- in order to run on actual images, much more pre-processing must be done.  We should compare the amount of time to compute the ELBO.

Still, last I checked, the elbo evaluation had indeed slowed down.  The only deepcopy is in the addition of sensitive floats, which should only happen per tile.  If that's in fact the problem then it's an easy fix.  In any case I'll look into it.

**Comment by jeff-regier** [comment]
It's just tests the speed of evaluating the ELBO. Certainly that's not the
only thing that matters---perhaps I should rename it "benchmark_elbo.jl".

**Comment by rgiordan** [comment]
As-is, the profiler profiles the whole thing, right?  Is that what you
attached here?  Easy enough to change.

So it used to be 20 seconds?

**Comment by rgiordan** [comment]
It would probably be helpful for me if the two of us went through this together sometime.  I ran the profiler myself, and if I'm reading it right the deepcopy operations indeed only cost about 5% of the total operation time.  It's not immediately obvious to me where to look next, and I know you have a lot more insight into this kind of thing than I do.

**Comment by rgiordan** [comment]
So the bulk of the computation is still in `accum_galaxy_pos!` and `accum_star_pos!`.  The only change since May to those functions is that we now have 

```
    dfs1m_dpix = NumType[f .* py1, f .* py2]
    dfs1m_dworld = wcs_jacobian' * dfs1m_dpix
    fs1m.d[gal_ids.u[1]] += dfs1m_dworld[1]
    fs1m.d[gal_ids.u[2]] += dfs1m_dworld[2]
```

This is to change the location derivatives from pixel to world coordinates, which you didn't have to do before because you were just using stamps.  I guess I assumed that the compiler would optimize away these extra assignments which I added for readability, but maybe not?

**Comment by rgiordan** [comment]
That turns out to make a difference, getting the elbo down to about 90 seconds.  Still looking to see where the rest might have gone.

**Comment by rgiordan** [comment]
Jeff, could you take a look at the diff and see if you have any ideas?

`git difftool 34bb28d improve_benchmark src/ElboDeriv.jl`

Looking at the profiles, each still spends the bulk of its time in `accum_pixel_source_stats`, which are not too much changed except for the jacobian, which is unavoidable.  The different numeric type arguments don't make any difference since each type is compiled separately, right?

**Comment by jeff-regier** [comment]
That's might understanding---each types get compiled separately. I should verify that the benchmark script hasn't changed substantially since the run at the end of May. I'll look into that tomorrow. If the Jacobian is getting calculated now, that could explain some of it. I didn't realize the deepcopy's were only taking a small fraction of the time---they just caught my eye when I was sending the profiler output to Kiren. Easiest way to get to the bottom of it is to compare profiler output from end of May to now...see what is slower that shouldn't be. There are some good tips for what to look for here:
http://julia.readthedocs.org/en/latest/manual/performance-tips/

**Comment by jeff-regier** [comment]
No substantive changes to the benchmark script that I see. Both generate blobs of images containing 100 sources, 1000x1000 pixels. I timed elbo evaluations for both after running the elbo once first, so as now to count time spend compiling the code (or to record memory use by the compiler).

May 27:

```
elapsed time: 40.375056588 seconds (2159979064 bytes allocated, 10.16% gc time)
```

Now

```
elapsed time: 214.080199721 seconds (19150760392 bytes allocated, 33.86% gc time)
```

Memory use is almost 10x higher now, so that's the problem. I've seen high memory use before when types are getting inferred at runtime rather than compile time. Several of the performance tips above are about that.

**Comment by rgiordan** [comment]
The remainder of the difference after the last two pulls is indeed entirely due to the memory allocation to do the reduce in the @parallel loop.  I stand corrected!  I'm surprised that something that occurs only once per tile is so expensive.

I'll look into darrays to start, it'll be good for me to learn about them anyway.

**Comment by rgiordan** [comment]
Fixed with https://github.com/jeff-regier/Celeste.jl/pull/72

**Comment by jeff-regier** [comment]
Using darrays doesn't strike me as a very promising research direction...
Are you still aiming for VI workshop paper? Not a very promising dev
direction either---darrays only solve the problem of distributing the data,
not "reducing" the output of each worker. Threading is a lot more promising
but likely too experimental right now.
