### ISSUE TITLE
Remove NLopt from REQUIRE file (?)

### ISSUE THREAD

**Issue by jeff-regier** [jeff-regier/Celeste.jl#94]
We've still have NLopt in the REQUIRE file, but presumably it would be easier to deploy our code on NERSC with fewer dependencies, and installing NLopt.jl takes compiling some C code. 

@rgiordan , you were saying we still need NLopt for a couple of unit tests, right? Are those tests essential? If this is a problem with negative curvature, might the trust region method have the same problems on the actual images that it has in the unit tests?

**Comment by rgiordan** [comment]
The problems come up in unit tests that optimize only one variable (e.g. a) while keeping all others fixed.   TR methods can't handle problems that have /only/ positive eigenvalues, and that's only happening here because we're just looking at one variable.  The actual images will not have this problem.  Maybe these tests are not essential, certainly not in the short-run.  You can see easily see which ones they are by searching for what code is calling the NLOPT optimize function.

**Comment by jeff-regier** [comment]
Great, let's remove then then. Down with dependencies!
